# Generated by Django 4.1.4 on 2023-01-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='images/')),
                ('pdf', models.FileField(upload_to='pdf/')),
            ],
        ),
    ]
